CREATE TABLE Orders (
  ID INT, 
  CUSTOMER_ID INT NOT NULL UNIQUE, 
  TOTAL_AMOUNT INT NOT NULL CHECK (TOTAL_AMOUNT > 0), 
  ORDER_STATUS VARCHAR(255) NOT NULL DEFAULT 'Pending', 
  SHIPPING_FEE INT CHECK (SHIPPING_FEE > 2), 
  PAYMENT_METHOD VARCHAR(255) NOT NULL,
  PAID VARCHAR(255)
); 
